spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 1234
    url: jdbc:mysql://localhost:3306/spring_boot_demo
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

aws:
  region: eu-central-1
  s3:
    buckets:
      customer: my-aws-bucket-spring-boot-rest-api

flyway:
  enabled: true
jwt:
  token:
    secret: springbootrestapi
    expired: 3600000